# Generated by Django 4.2.4 on 2023-08-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meigen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='meigen',
            table='meigen',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='user_group',
        ),
    ]
